# Generated by Django 6.0.1 on 2026-01-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0003_rename_proyecto_2025_obra_meta_2025_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obra',
            old_name='proyecto_2025_presupuesto',
            new_name='proyecto_presupuesto',
        ),
        migrations.RenameField(
            model_name='obra',
            old_name='puntuacion_final',
            new_name='puntuacion_final_ponderada',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='impacto_social',
        ),
        migrations.AddField(
            model_name='obra',
            name='impacto_social_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
