# Generated by Django 6.0.1 on 2026-01-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poa', '0004_rename_proyecto_2025_presupuesto_obra_proyecto_presupuesto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='beneficiarios_num',
            field=models.BigIntegerField(default=0),
        ),
    ]
