# Generated by Sprint 3 - Fase 2: Optimización con Índices PostgreSQL
# Fecha: 24 de enero de 2026

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Sprint 3 - Fase 2: Índices de Base de Datos para Optimización de Queries
    
    Crea índices en los campos más frecuentemente filtrados y ordenados:
    - area_responsable (filtrado en dashboard y búsquedas)
    - estatus_general (filtrado por estado)
    - fecha_termino_prog (ordenamiento temporal)
    - fecha_inicio_prog (filtrado de proyectos activos)
    - ultima_actualizacion (ordenamiento de actividad reciente)
    - puntuacion_final_ponderada (ordenamiento por prioridad)
    - avance_fisico_pct (ordenamiento por progreso)
    
    Beneficio esperado:
    - Queries con WHERE en estos campos: -90% tiempo
    - Queries con ORDER BY: -80% tiempo
    - Paginación: -85% tiempo
    
    Impacto en BD:
    - Espacio adicional: ~5-10MB (depende del dataset)
    - Inserts ligeramente más lentos (pero updates son raros)
    """

    dependencies = [
        ('poa', '0005_obra_beneficiarios_num'),
    ]

    operations = [
        # Índice 1: Filtrado por área responsable
        # Usado en: dashboard, filtros, búsquedas por dirección
        migrations.AddIndex(
            model_name='obra',
            index=models.Index(
                fields=['area_responsable'],
                name='poa_obra_area_idx'
            ),
        ),
        
        # Índice 2: Filtrado por estado general
        # Usado en: filtros de estado, KPIs, dashboard
        migrations.AddIndex(
            model_name='obra',
            index=models.Index(
                fields=['estatus_general'],
                name='poa_obra_estatus_idx'
            ),
        ),
        
        # Índice 3: Ordenamiento por fecha de término programada
        # Usado en: próximas entregas, timeline, predicciones
        migrations.AddIndex(
            model_name='obra',
            index=models.Index(
                fields=['fecha_termino_prog'],
                name='poa_obra_fecha_term_idx'
            ),
        ),
        
        # Índice 4: Filtrado por fecha de inicio programada
        # Usado en: proyectos activos, timeline, gantt
        migrations.AddIndex(
            model_name='obra',
            index=models.Index(
                fields=['fecha_inicio_prog'],
                name='poa_obra_fecha_ini_idx'
            ),
        ),
        
        # Índice 5: Ordenamiento por última actualización
        # Usado en: actividad reciente, cambios recientes
        migrations.AddIndex(
            model_name='obra',
            index=models.Index(
                fields=['-ultima_actualizacion'],  # Descendente para ORDER BY DESC
                name='poa_obra_ultima_act_idx'
            ),
        ),
        
        # Índice 6: Ordenamiento por puntuación final ponderada
        # Usado en: proyectos críticos, priorización, hitos
        migrations.AddIndex(
            model_name='obra',
            index=models.Index(
                fields=['-puntuacion_final_ponderada'],  # Descendente
                name='poa_obra_punt_final_idx'
            ),
        ),
        
        # Índice 7: Ordenamiento por avance físico
        # Usado en: proyectos con mayor/menor avance, filtros
        migrations.AddIndex(
            model_name='obra',
            index=models.Index(
                fields=['-avance_fisico_pct'],  # Descendente
                name='poa_obra_avance_idx'
            ),
        ),
        
        # Índice 8: Compuesto para filtro común (área + avance)
        # Usado en: dashboard por dirección con ordenamiento por avance
        # Beneficio: Evita sorting en queries complejas
        migrations.AddIndex(
            model_name='obra',
            index=models.Index(
                fields=['area_responsable', '-avance_fisico_pct'],
                name='poa_obra_area_avance_idx'
            ),
        ),
        
        # Índice 9: Compuesto para timeline (fechas + estado)
        # Usado en: queries de proyectos activos con rango de fechas
        migrations.AddIndex(
            model_name='obra',
            index=models.Index(
                fields=['estatus_general', 'fecha_termino_prog'],
                name='poa_obra_estado_fecha_idx'
            ),
        ),
        
        # Índice 10: Para búsqueda de texto en alcaldías
        # PostgreSQL: índice GIN para búsquedas LIKE/ILIKE más rápidas
        # Nota: Si usas PostgreSQL, considera cambiar a GIN index
        migrations.AddIndex(
            model_name='obra',
            index=models.Index(
                fields=['alcaldias'],
                name='poa_obra_alcaldias_idx'
            ),
        ),
    ]
